Output assets/kubectl-peek-exec.gif

Set Shell "zsh"
Set FontSize 22
Set Width 1200
Set Height 700
Set TypingSpeed 45ms
Set Theme "Dracula"

Type "kubectl-peek exec"
Enter
Sleep 1500ms

# Select the second Pod.
Down
Enter
Sleep 1500ms

# Select the first container.
Enter
Sleep 1200ms

# Run a simple command inside the container.
Type "clear"
Enter
Sleep 1200ms
Type "ls"
Enter
Sleep 1200ms

# Leave the container shell.
Type "exit"
Enter
Sleep 1200ms
